=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FuseClient::SpendPowerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SpendPowerApi' do
  before do
    # run before each test
    @api_instance = FuseClient::SpendPowerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpendPowerApi' do
    it 'should create an instance of SpendPowerApi' do
      expect(@api_instance).to be_instance_of(FuseClient::SpendPowerApi)
    end
  end

  # unit tests for delete_spend_power
  # Delete spend power customization
  # @param spend_power_id 
  # @param fuse_client_id 
  # @param fuse_api_key 
  # @param [Hash] opts the optional parameters
  # @return [DeleteSpendPowerResponse]
  describe 'delete_spend_power test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_spend_power_customization
  # Get spend power customization
  # @param spend_power_customization_id 
  # @param fuse_client_id 
  # @param fuse_api_key 
  # @param [Hash] opts the optional parameters
  # @return [GetSpendPowerCustomizationResponse]
  describe 'get_spend_power_customization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
