=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FuseClient::SpendPowerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SpendPowerApi' do
  before do
    # run before each test
    @api_instance = FuseClient::SpendPowerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpendPowerApi' do
    it 'should create an instance of SpendPowerApi' do
      expect(@api_instance).to be_instance_of(FuseClient::SpendPowerApi)
    end
  end

  # unit tests for delete_spend_power
  # @param spend_power_id 
  # @param fuse_client_id 
  # @param fuse_api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :plaid_client_id 
  # @option opts [String] :plaid_secret 
  # @option opts [String] :teller_application_id 
  # @option opts [String] :teller_certificate 
  # @option opts [String] :teller_private_key 
  # @option opts [String] :teller_token_signing_key 
  # @option opts [String] :teller_signing_secret 
  # @option opts [String] :mx_client_id 
  # @option opts [String] :mx_api_key 
  # @option opts [String] :snaptrade_client_id 
  # @option opts [String] :snaptrade_consumer_key 
  # @option opts [String] :flinks_customer_id 
  # @option opts [String] :flinks_us_instance_id 
  # @option opts [String] :flinks_ca_instance_id 
  # @option opts [String] :finicity_partner_id 
  # @option opts [String] :finicity_partner_secret 
  # @option opts [String] :finicity_app_key 
  # @return [DeleteSpendPowerResponse]
  describe 'delete_spend_power test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
