=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::AccountSubType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::AccountSubType do
  let(:instance) { FuseClient::AccountSubType.new }

  describe 'test an instance of AccountSubType' do
    it 'should create an instance of AccountSubType' do
      expect(instance).to be_instance_of(FuseClient::AccountSubType)
    end
  end
end
