=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::AssetReportAccountsInnerBalance
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::AssetReportAccountsInnerBalance do
  let(:instance) { FuseClient::AssetReportAccountsInnerBalance.new }

  describe 'test an instance of AssetReportAccountsInnerBalance' do
    it 'should create an instance of AssetReportAccountsInnerBalance' do
      expect(instance).to be_instance_of(FuseClient::AssetReportAccountsInnerBalance)
    end
  end
  describe 'test attribute "available"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "current"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "iso_currency_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
