=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::ConsumerRiskReportTimeFrame
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::ConsumerRiskReportTimeFrame do
  let(:instance) { FuseClient::ConsumerRiskReportTimeFrame.new }

  describe 'test an instance of ConsumerRiskReportTimeFrame' do
    it 'should create an instance of ConsumerRiskReportTimeFrame' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FuseClient::ConsumerRiskReportTimeFrame)
    end
  end

end
