=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::CountryCode
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::CountryCode do
  let(:instance) { FuseClient::CountryCode.new }

  describe 'test an instance of CountryCode' do
    it 'should create an instance of CountryCode' do
      expect(instance).to be_instance_of(FuseClient::CountryCode)
    end
  end
end
