=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::CreateConsumerRiskReportCustomizationRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::CreateConsumerRiskReportCustomizationRequest do
  let(:instance) { FuseClient::CreateConsumerRiskReportCustomizationRequest.new }

  describe 'test an instance of CreateConsumerRiskReportCustomizationRequest' do
    it 'should create an instance of CreateConsumerRiskReportCustomizationRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FuseClient::CreateConsumerRiskReportCustomizationRequest)
    end
  end

  describe 'test attribute "timeframe"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "min_limit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "max_limit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "risk_tolerance"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
