=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::CreateLinkTokenRequestSnaptradeConfig
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::CreateLinkTokenRequestSnaptradeConfig do
  let(:instance) { FuseClient::CreateLinkTokenRequestSnaptradeConfig.new }

  describe 'test an instance of CreateLinkTokenRequestSnaptradeConfig' do
    it 'should create an instance of CreateLinkTokenRequestSnaptradeConfig' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FuseClient::CreateLinkTokenRequestSnaptradeConfig)
    end
  end

  describe 'test attribute "connection_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["read", "trade"])
      # validator.allowable_values.each do |value|
      #   expect { instance.connection_type = value }.not_to raise_error
      # end
    end
  end

end
