=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::FinQLFeatureOneOf1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::FinQLFeatureOneOf1 do
  let(:instance) { FuseClient::FinQLFeatureOneOf1.new }

  describe 'test an instance of FinQLFeatureOneOf1' do
    it 'should create an instance of FinQLFeatureOneOf1' do
      expect(instance).to be_instance_of(FuseClient::FinQLFeatureOneOf1)
    end
  end
  describe 'test attribute "individual_merchant"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
