=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::FinancialConnectionsInvestmentSecurityType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::FinancialConnectionsInvestmentSecurityType do
  let(:instance) { FuseClient::FinancialConnectionsInvestmentSecurityType.new }

  describe 'test an instance of FinancialConnectionsInvestmentSecurityType' do
    it 'should create an instance of FinancialConnectionsInvestmentSecurityType' do
      expect(instance).to be_instance_of(FuseClient::FinancialConnectionsInvestmentSecurityType)
    end
  end
end
