=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::GetInvestmentHoldingsResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::GetInvestmentHoldingsResponse do
  let(:instance) { FuseClient::GetInvestmentHoldingsResponse.new }

  describe 'test an instance of GetInvestmentHoldingsResponse' do
    it 'should create an instance of GetInvestmentHoldingsResponse' do
      expect(instance).to be_instance_of(FuseClient::GetInvestmentHoldingsResponse)
    end
  end
  describe 'test attribute "accounts"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "holdings"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "securities"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
