=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::GetEntityResponseAggregatorAccessTokensMx
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::GetEntityResponseAggregatorAccessTokensMx do
  let(:instance) { FuseClient::GetEntityResponseAggregatorAccessTokensMx.new }

  describe 'test an instance of GetEntityResponseAggregatorAccessTokensMx' do
    it 'should create an instance of GetEntityResponseAggregatorAccessTokensMx' do
      expect(instance).to be_instance_of(FuseClient::GetEntityResponseAggregatorAccessTokensMx)
    end
  end
  describe 'test attribute "user_guid"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "member_guid"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
