=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::GetEntityResponseAggregatorAccessTokensInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::GetEntityResponseAggregatorAccessTokensInner do
  let(:instance) { FuseClient::GetEntityResponseAggregatorAccessTokensInner.new }

  describe 'test an instance of GetEntityResponseAggregatorAccessTokensInner' do
    it 'should create an instance of GetEntityResponseAggregatorAccessTokensInner' do
      expect(instance).to be_instance_of(FuseClient::GetEntityResponseAggregatorAccessTokensInner)
    end
  end
  describe 'test attribute "financial_connection_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "plaid"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "teller"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "mx"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
