=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::GetFinancialConnectionsBalanceRequestOptions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::GetFinancialConnectionsBalanceRequestOptions do
  let(:instance) { FuseClient::GetFinancialConnectionsBalanceRequestOptions.new }

  describe 'test an instance of GetFinancialConnectionsBalanceRequestOptions' do
    it 'should create an instance of GetFinancialConnectionsBalanceRequestOptions' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FuseClient::GetFinancialConnectionsBalanceRequestOptions)
    end
  end

  describe 'test attribute "remote_account_ids"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
