=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FuseClient::SpendPowerCustomization
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FuseClient::SpendPowerCustomization do
  let(:instance) { FuseClient::SpendPowerCustomization.new }

  describe 'test an instance of SpendPowerCustomization' do
    it 'should create an instance of SpendPowerCustomization' do
      expect(instance).to be_instance_of(FuseClient::SpendPowerCustomization)
    end
  end
  describe 'test attribute "timeframe"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["daily", "weekly", "monthly"])
      # validator.allowable_values.each do |value|
      #   expect { instance.timeframe = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "min_limit"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "max_limit"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
