=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module FuseClient
  class FinancialConnectionsInvestmentSecurityType
    CASH = "cash".freeze
    CRYPTOCURRENCY = "cryptocurrency".freeze
    DERIVATIVE = "derivative".freeze
    EQUITY = "equity".freeze
    ETF = "etf".freeze
    FIXED_INCOME = "fixed_income".freeze
    LOAN = "loan".freeze
    MUTUAL_FUND = "mutual_fund".freeze
    OTHER = "other".freeze
    GLOBAL_DEPOSITARY_RECEIPT = "global_depositary_receipt".freeze
    OPEN_ENDED_FUND = "open_ended_fund".freeze
    RIGHT = "right".freeze
    TEMPORARY = "temporary".freeze
    WARRANT = "warrant".freeze
    CLOSED_ENDED_FUND = "closed_ended_fund".freeze
    COMMON_STOCK = "common_stock".freeze
    EXCHANGE_TRADED_FUND = "exchange_traded_fund".freeze
    BOND = "bond".freeze
    AMERICAN_DEPOSITARY_RECEIPT = "american_depositary_receipt".freeze
    UNIT = "unit".freeze
    STRUCTURED_PRODUCT = "structured_product".freeze
    PREFERRED_STOCK = "preferred_stock".freeze
    REAL_ESTATE = "real_estate".freeze
    AUTOMOBILE = "automobile".freeze
    DELISTED_OR_DEFUNCT_ASSET = "delisted_or_defunct_asset".freeze
     = "-".freeze

    def self.all_vars
      @all_vars ||= [CASH, CRYPTOCURRENCY, DERIVATIVE, EQUITY, ETF, FIXED_INCOME, LOAN, MUTUAL_FUND, OTHER, GLOBAL_DEPOSITARY_RECEIPT, OPEN_ENDED_FUND, RIGHT, TEMPORARY, WARRANT, CLOSED_ENDED_FUND, COMMON_STOCK, EXCHANGE_TRADED_FUND, BOND, AMERICAN_DEPOSITARY_RECEIPT, UNIT, STRUCTURED_PRODUCT, PREFERRED_STOCK, REAL_ESTATE, AUTOMOBILE, DELISTED_OR_DEFUNCT_ASSET, ].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if FinancialConnectionsInvestmentSecurityType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #FinancialConnectionsInvestmentSecurityType"
    end
  end
end
