=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module FuseClient
  class FuseApiErrorCode
    ASSET_REPORT_GENERATION_FAILED = "asset_report_generation_failed".freeze
    ASSET_REPORT_NOT_READY = "asset_report_not_ready".freeze
    CLIENT_ERROR = "client_error".freeze
    INVALID_HEADERS = "invalid_headers".freeze
    INVALID_REQUEST_BODY = "invalid_request_body".freeze
    INTERNAL_SERVER_ERROR = "internal_server_error".freeze
    ORGANIZATION_NOT_FOUND = "organization_not_found".freeze
    ENTITY_NOT_FOUND = "entity_not_found".freeze
    SESSION_NOT_FOUND = "session_not_found".freeze
    FINANCIAL_INSTITUTION_NOT_FOUND = "financial_institution_not_found".freeze
    CONSUMER_RISK_REPORT_NOT_FOUND = "consumer_risk_report_not_found".freeze
    CONSUMER_RISK_REPORT_CUSTOMIZATION_NOT_FOUND = "consumer_risk_report_customization_not_found".freeze
    MISSING_ACCESS_TOKEN = "missing_access_token".freeze
    MISSING_PLAID_CLIENT_ID_HEADER = "missing_plaid_client_id_header".freeze
    MISSING_PLAID_SECRET_HEADER = "missing_plaid_secret_header".freeze
    MISSING_MX_CLIENT_ID_HEADER = "missing_mx_client_id_header".freeze
    MISSING_MX_API_KEY_HEADER = "missing_mx_api_key_header".freeze
    MISSING_TELLER_PRIVATE_KEY_HEADER = "missing_teller_private_key_header".freeze
    MISSING_TELLER_CERTIFICATE_HEADER = "missing_teller_certificate_header".freeze
    MISSING_TELLER_APPLICATION_ID_HEADER = "missing_teller_application_id_header".freeze
    MISSING_TELLER_SIGNING_SECRET_HEADER = "missing_teller_signing_secret_header".freeze
    MISSING_SNAPTRADE_CLIENT_ID_HEADER = "missing_snaptrade_client_id_header".freeze
    MISSING_SNAPTRADE_CONSUMER_KEY_HEADER = "missing_snaptrade_consumer_key_header".freeze
    MISSING_FLINKS_CA_CUSTOMER_ID_HEADER = "missing_flinks_ca_customer_id_header".freeze
    MISSING_FLINKS_US_CUSTOMER_ID_HEADER = "missing_flinks_us_customer_id_header".freeze
    MISSING_FLINKS_CA_INSTANCE_ID_HEADER = "missing_flinks_ca_instance_id_header".freeze
    MISSING_FLINKS_US_INSTANCE_ID_HEADER = "missing_flinks_us_instance_id_header".freeze
    MISSING_MONO_PUBLIC_KEY_HEADER = "missing_mono_public_key_header".freeze
    MISSING_MONO_SECRET_KEY_HEADER = "missing_mono_secret_key_header".freeze
    MISSING_MONO_WEBHOOK_SECRET_HEADER = "missing_mono_webhook_secret_header".freeze
    MISSING_TRUELAYER_CLIENT_ID_HEADER = "missing_truelayer_client_id_header".freeze
    MISSING_TRUELAYER_CLIENT_SECRET_HEADER = "missing_truelayer_client_secret_header".freeze
    MISSING_TRUELAYER_REDIRECT_URI_HEADER = "missing_truelayer_redirect_uri_header".freeze
    MISSING_FINVERSE_CLIENT_ID_HEADER = "missing_finverse_client_id_header".freeze
    MISSING_FINVERSE_CLIENT_SECRET_HEADER = "missing_finverse_client_secret_header".freeze
    MISSING_FINVERSE_REDIRECT_URI_HEADER = "missing_finverse_redirect_uri_header".freeze
    MISSING_BASIQ_API_KEY_HEADER = "missing_basiq_api_key_header".freeze
    MISSING_BELVO_SECRET_ID_HEADER = "missing_belvo_secret_id_header".freeze
    MISSING_BELVO_SECRET_PASSWORD_HEADER = "missing_belvo_secret_password_header".freeze
    MISSING_FUSE_VERIFICATION_HEADER = "missing_fuse_verification_header".freeze
    AGGREGATOR_ERROR = "aggregator_error".freeze
    AGGREGATOR_DISCONNECTED_ERROR = "aggregator_disconnected_error".freeze
    AGGREGATOR_CONNECTION_FINISHED_ERROR = "aggregator_connection_finished_error".freeze
    AGGREGATOR_RATE_LIMIT_ERROR = "aggregator_rate_limit_error".freeze
    REQUEST_BODY_MISSING = "request_body_missing".freeze
    REQUEST_CONTENT_TYPE_INVALID = "request_content_type_invalid".freeze
    REQUEST_BODY_INVALID_JSON = "request_body_invalid_json".freeze
    WEBHOOK_ERROR = "webhook_error".freeze
    TIMEOUT = "timeout".freeze
    INVALID_CERTIFICATE = "invalid_certificate".freeze
    INVALID_PRIVATE_KEY = "invalid_private_key".freeze
    OTHER = "other".freeze

    def self.all_vars
      @all_vars ||= [ASSET_REPORT_GENERATION_FAILED, ASSET_REPORT_NOT_READY, CLIENT_ERROR, INVALID_HEADERS, INVALID_REQUEST_BODY, INTERNAL_SERVER_ERROR, ORGANIZATION_NOT_FOUND, ENTITY_NOT_FOUND, SESSION_NOT_FOUND, FINANCIAL_INSTITUTION_NOT_FOUND, CONSUMER_RISK_REPORT_NOT_FOUND, CONSUMER_RISK_REPORT_CUSTOMIZATION_NOT_FOUND, MISSING_ACCESS_TOKEN, MISSING_PLAID_CLIENT_ID_HEADER, MISSING_PLAID_SECRET_HEADER, MISSING_MX_CLIENT_ID_HEADER, MISSING_MX_API_KEY_HEADER, MISSING_TELLER_PRIVATE_KEY_HEADER, MISSING_TELLER_CERTIFICATE_HEADER, MISSING_TELLER_APPLICATION_ID_HEADER, MISSING_TELLER_SIGNING_SECRET_HEADER, MISSING_SNAPTRADE_CLIENT_ID_HEADER, MISSING_SNAPTRADE_CONSUMER_KEY_HEADER, MISSING_FLINKS_CA_CUSTOMER_ID_HEADER, MISSING_FLINKS_US_CUSTOMER_ID_HEADER, MISSING_FLINKS_CA_INSTANCE_ID_HEADER, MISSING_FLINKS_US_INSTANCE_ID_HEADER, MISSING_MONO_PUBLIC_KEY_HEADER, MISSING_MONO_SECRET_KEY_HEADER, MISSING_MONO_WEBHOOK_SECRET_HEADER, MISSING_TRUELAYER_CLIENT_ID_HEADER, MISSING_TRUELAYER_CLIENT_SECRET_HEADER, MISSING_TRUELAYER_REDIRECT_URI_HEADER, MISSING_FINVERSE_CLIENT_ID_HEADER, MISSING_FINVERSE_CLIENT_SECRET_HEADER, MISSING_FINVERSE_REDIRECT_URI_HEADER, MISSING_BASIQ_API_KEY_HEADER, MISSING_BELVO_SECRET_ID_HEADER, MISSING_BELVO_SECRET_PASSWORD_HEADER, MISSING_FUSE_VERIFICATION_HEADER, AGGREGATOR_ERROR, AGGREGATOR_DISCONNECTED_ERROR, AGGREGATOR_CONNECTION_FINISHED_ERROR, AGGREGATOR_RATE_LIMIT_ERROR, REQUEST_BODY_MISSING, REQUEST_CONTENT_TYPE_INVALID, REQUEST_BODY_INVALID_JSON, WEBHOOK_ERROR, TIMEOUT, INVALID_CERTIFICATE, INVALID_PRIVATE_KEY, OTHER].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if FuseApiErrorCode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #FuseApiErrorCode"
    end
  end
end
