=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module FuseClient
  class FuseApiErrorType
    AUTH_ERROR = "auth_error".freeze
    NOT_FOUND = "not_found".freeze
    BAD_REQUEST = "bad_request".freeze
    SERVER_ERROR = "server_error".freeze

    def self.all_vars
      @all_vars ||= [AUTH_ERROR, NOT_FOUND, BAD_REQUEST, SERVER_ERROR].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if FuseApiErrorType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #FuseApiErrorType"
    end
  end
end
