=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module FuseClient
  class TransactionCategoryDetailed
    AUTO_INSURANCE = "auto_insurance".freeze
    AUTO_PAYMENT = "auto_payment".freeze
    GAS = "gas".freeze
    PARKING = "parking".freeze
    PUBLIC_TRANSPORTATION = "public_transportation".freeze
    SERVICE_AND_PARTS = "service_and_parts".freeze
    DOMAIN_NAMES = "domain_names".freeze
    FRAUD_PROTECTION = "fraud_protection".freeze
    HOME_PHONE = "home_phone".freeze
    HOSTING = "hosting".freeze
    INTERNET = "internet".freeze
    MOBILE_PHONE = "mobile_phone".freeze
    TELEVISION = "television".freeze
    UTILITIES = "utilities".freeze
    ADVERTISING = "advertising".freeze
    LEGAL = "legal".freeze
    OFFICE_SUPPLIES = "office_supplies".freeze
    PRINTING = "printing".freeze
    SHIPPING = "shipping".freeze
    BOOKS_AND_SUPPLIES = "books_and_supplies".freeze
    STUDENT_LOAN = "student_loan".freeze
    TUITION = "tuition".freeze
    AMUSEMENT = "amusement".freeze
    ARTS = "arts".freeze
    MOVIES_AND_DVDS = "movies_and_dvds".freeze
    MUSIC = "music".freeze
    NEWSPAPERS_AND_MAGAZINES = "newspapers_and_magazines".freeze
    ATM_FEE = "atm_fee".freeze
    BANKING_FEE = "banking_fee".freeze
    FINANCE_CHARGE = "finance_charge".freeze
    LATE_FEE = "late_fee".freeze
    SERVICE_FEE = "service_fee".freeze
    TRADE_COMMISSIONS = "trade_commissions".freeze
    FINANCIAL_ADVISOR = "financial_advisor".freeze
    LIFE_INSURANCE = "life_insurance".freeze
    ALCOHOL_AND_BARS = "alcohol_and_bars".freeze
    COFFEE_SHOPS = "coffee_shops".freeze
    FAST_FOOD = "fast_food".freeze
    GROCERIES = "groceries".freeze
    RESTAURANTS = "restaurants".freeze
    CHARITY = "charity".freeze
    GIFT = "gift".freeze
    DENTIST = "dentist".freeze
    DOCTOR = "doctor".freeze
    EYECARE = "eyecare".freeze
    GYM = "gym".freeze
    HEALTH_INSURANCE = "health_insurance".freeze
    PHARMACY = "pharmacy".freeze
    SPORTS = "sports".freeze
    FURNISHINGS = "furnishings".freeze
    HOME_IMPROVEMENT = "home_improvement".freeze
    HOME_INSURANCE = "home_insurance".freeze
    HOME_SERVICES = "home_services".freeze
    HOME_SUPPLIES = "home_supplies".freeze
    LAWN_AND_GARDEN = "lawn_and_garden".freeze
    MORTGAGE_AND_RENT = "mortgage_and_rent".freeze
    BONUS = "bonus".freeze
    INTEREST_INCOME = "interest_income".freeze
    PAYCHECK = "paycheck".freeze
    REIMBURSEMENT = "reimbursement".freeze
    RENTAL_INCOME = "rental_income".freeze
    RETURNED_PURCHASE = "returned_purchase".freeze
    BUY = "buy".freeze
    DEPOSIT = "deposit".freeze
    DIVIDEND_AND_CAP_GAINS = "dividend_and_cap_gains".freeze
    SELL = "sell".freeze
    WITHDRAWAL = "withdrawal".freeze
    ALLOWANCE = "allowance".freeze
    BABY_SUPPLIES = "baby_supplies".freeze
    BABYSITTER_AND_DAYCARE = "babysitter_and_daycare".freeze
    CHILD_SUPPORT = "child_support".freeze
    KIDS_ACTIVITIES = "kids_activities".freeze
    TOYS = "toys".freeze
    HAIR = "hair".freeze
    LAUNDRY = "laundry".freeze
    SPA_AND_MASSAGE = "spa_and_massage".freeze
    PET_FOOD_AND_SUPPLIES = "pet_food_and_supplies".freeze
    PET_GROOMING = "pet_grooming".freeze
    VETERINARY = "veterinary".freeze
    BOOKS = "books".freeze
    CLOTHING = "clothing".freeze
    HOBBIES = "hobbies".freeze
    SPORTING_GOODS = "sporting_goods".freeze
    FEDERAL_TAX = "federal_tax".freeze
    LOCAL_TAX = "local_tax".freeze
    PROPERTY_TAX = "property_tax".freeze
    SALES_TAX = "sales_tax".freeze
    STATE_TAX = "state_tax".freeze
    CREDIT_CARD_PAYMENT = "credit_card_payment".freeze
    TRANSFER_FOR_CASH_SPENDING = "transfer_for_cash_spending".freeze
    MORTGAGE_PAYMENT = "mortgage_payment".freeze
    AIR_TRAVEL = "air_travel".freeze
    HOTEL = "hotel".freeze
    RENTAL_CAR_AND_TAXI = "rental_car_and_taxi".freeze
    VACATION = "vacation".freeze
    CASH = "cash".freeze
    CHECK = "check".freeze

    def self.all_vars
      @all_vars ||= [AUTO_INSURANCE, AUTO_PAYMENT, GAS, PARKING, PUBLIC_TRANSPORTATION, SERVICE_AND_PARTS, DOMAIN_NAMES, FRAUD_PROTECTION, HOME_PHONE, HOSTING, INTERNET, MOBILE_PHONE, TELEVISION, UTILITIES, ADVERTISING, LEGAL, OFFICE_SUPPLIES, PRINTING, SHIPPING, BOOKS_AND_SUPPLIES, STUDENT_LOAN, TUITION, AMUSEMENT, ARTS, MOVIES_AND_DVDS, MUSIC, NEWSPAPERS_AND_MAGAZINES, ATM_FEE, BANKING_FEE, FINANCE_CHARGE, LATE_FEE, SERVICE_FEE, TRADE_COMMISSIONS, FINANCIAL_ADVISOR, LIFE_INSURANCE, ALCOHOL_AND_BARS, COFFEE_SHOPS, FAST_FOOD, GROCERIES, RESTAURANTS, CHARITY, GIFT, DENTIST, DOCTOR, EYECARE, GYM, HEALTH_INSURANCE, PHARMACY, SPORTS, FURNISHINGS, HOME_IMPROVEMENT, HOME_INSURANCE, HOME_SERVICES, HOME_SUPPLIES, LAWN_AND_GARDEN, MORTGAGE_AND_RENT, BONUS, INTEREST_INCOME, PAYCHECK, REIMBURSEMENT, RENTAL_INCOME, RETURNED_PURCHASE, BUY, DEPOSIT, DIVIDEND_AND_CAP_GAINS, SELL, WITHDRAWAL, ALLOWANCE, BABY_SUPPLIES, BABYSITTER_AND_DAYCARE, CHILD_SUPPORT, KIDS_ACTIVITIES, TOYS, HAIR, LAUNDRY, SPA_AND_MASSAGE, PET_FOOD_AND_SUPPLIES, PET_GROOMING, VETERINARY, BOOKS, CLOTHING, HOBBIES, SPORTING_GOODS, FEDERAL_TAX, LOCAL_TAX, PROPERTY_TAX, SALES_TAX, STATE_TAX, CREDIT_CARD_PAYMENT, TRANSFER_FOR_CASH_SPENDING, MORTGAGE_PAYMENT, AIR_TRAVEL, HOTEL, RENTAL_CAR_AND_TAXI, VACATION, CASH, CHECK].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TransactionCategoryDetailed.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TransactionCategoryDetailed"
    end
  end
end
