=begin
#Fuse

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module FuseClient
  class TransactionCategoryPrimary
    INCOME = "income".freeze
    TRANSFER_IN = "transfer_in".freeze
    TRANSFER_OUT = "transfer_out".freeze
    LOAN_PAYMENTS = "loan_payments".freeze
    BANK_FEES = "bank_fees".freeze
    ENTERTAINMENT = "entertainment".freeze
    FOOD_AND_DRINK = "food_and_drink".freeze
    GENERAL_MERCHANDISE = "general_merchandise".freeze
    HOME_IMPROVEMENT = "home_improvement".freeze
    MEDICAL = "medical".freeze
    PERSONAL_CARE = "personal_care".freeze
    GENERAL_SERVICES = "general_services".freeze
    GOVERNMENT_AND_NON_PROFIT = "government_and_non_profit".freeze
    TRANSPORTATION = "transportation".freeze
    TRAVEL = "travel".freeze
    RENT_AND_UTILITIES = "rent_and_utilities".freeze

    def self.all_vars
      @all_vars ||= [INCOME, TRANSFER_IN, TRANSFER_OUT, LOAN_PAYMENTS, BANK_FEES, ENTERTAINMENT, FOOD_AND_DRINK, GENERAL_MERCHANDISE, HOME_IMPROVEMENT, MEDICAL, PERSONAL_CARE, GENERAL_SERVICES, GOVERNMENT_AND_NON_PROFIT, TRANSPORTATION, TRAVEL, RENT_AND_UTILITIES].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TransactionCategoryPrimary.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TransactionCategoryPrimary"
    end
  end
end
